server: pve-dev

allow:
  flight: true

commands:
  modmode:
    activate:
      before: [ ]
      after: [ ]
    deactivate:
      before: [ ]
      after: [ ]
  adminmode:
    activate:
      before: [ ]
      after: [ ]
    deactivate:
      before: [ ]
      after: [ ]

debug:
  playerdata: false

permissions:
  modmode-group: ModMode
  moderator-group: moderators
  adminmode-group: AdminMode
  admin-group: admins
  persistent-groups: []
  worlds: []
