vanish-delay-ticks: 20

allow:
  flight: true
  collisions: true

commands:
  activate:
    before: []
    after:
    - /we cui
    - /lb toolblock on
  deactivate:
    before: []
    after: []

debug:
  playerdata: false

permissions:
  modmode-group: ModMode
  moderator-group: moderators
  persistent-groups: []
  worlds: []
