name: ModMode
version: ${project.version}
description: ${project.description}

authors: [Travis Watkins, Deaygo]
website: ${project.url}

main: nu.nerd.modmode.ModMode
softdepend: [TagAPI, LogBlock]
depend: [LuckPerms, NerdBoard]

api-version: 1.13

commands:
  vanish:
    description: Vanish, or check vanish state with /vanish check.
    permission: modmode.vanish
  unvanish:
    description: Unvanish.
    permission: modmode.unvanish
  vanishlist:
    description: Show list of invisible people
    permission: modmode.vanishlist
  modmode:
    description: Toggle ModMode
    permission: modmode.toggle
  savekit:
    description: Set the ModMode kit.
    permission: modmode.op

permissions:
  modmode:
    description: Allow the player all Vanish-related permissions
    children:
      modmode.vanishlist:
        description: Allow the player to see the vanish list
  modmode.toggle:
    description: Allow the player to enter ModMode

  modmode.op:
    description: Allow use of /modmode save and /modmode reload admin commands.
