name: ModMode
version: ${project.version}
description: ${project.description}

authors: [Travis Watkins, Deaygo]
website: ${project.url}

main: nu.nerd.modmode.ModMode
softdepend: [CoreProtect]
depend: [VanishNoPacket, TAB, LuckPerms]

api-version: 1.20

commands:
  vanish:
    description: Vanish, or check vanish state with /vanish check.
    permission: modmode.vanish
  unvanish:
    description: Unvanish.
    permission: modmode.unvanish
  reloadmodmode:
    description: Reload the configuration file for ModMode.
    permission: modmode.reload

permissions:
  modmode:
    description: Allow the player all Vanish-related permissions

  modmode.reload:
    description: Allow use of /modmode save and /modmode reload admin commands.
